# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Robocubs
paginate:       5
baseurl:        "https://robocubs.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Robocubs Team
  url:          https://robocubs.com
  email:        robocubs@robocubs.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/Robocubs/robocubs.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed